some ui changes
sunset-mod/Sunset pull request #12
Opened 2024-02-08 09:05 UTC by danilwhale

use "Vendetta/Sunset" instead of "Sunset" inside unproxied plugin installation warning
also add links to vendetta server/github 🥺

2024-02-08 13:20 UTC, Ushie requested changes

2024-02-08 13:20 UTC, Ushie commented on src/lib/constants.ts
> +export const VENDETTA_DISCORD_SERVER = "https://discord.gg/vendetta-mod";
Use a permanent invite URL, the vanity will likely be lost due to the server archival

2024-02-08 13:20 UTC, Ushie commented on src/ui/settings/data.tsx
> +                                content: "The plugin you are trying to install has not been proxied/verified by Vendetta/Sunset staff. Are you sure you want to continue?",
This is Sunset, Vendetta cannot verify plugins on our behalf

2024-02-08 13:20 UTC, Ushie commented on src/ui/settings/pages/General.tsx
> +                    />
Instead of duplicating this, forEach would be more pleasant

2024-02-08 13:55 UTC, danilwhale commented on src/lib/constants.ts
> +export const VENDETTA_DISCORD_SERVER = "https://discord.gg/vendetta-mod";
i dont know permanent url, #info channel is locked, so i used vendetta-mod

2024-02-08 14:20 UTC, riivx commented on src/lib/constants.ts
> +export const VENDETTA_DISCORD_SERVER = "https://discord.gg/vendetta-mod";
> i dont know permanent url

simply get it from the org. it's https://discord.gg/n9QQ4XhhJP btw

2024-02-08 14:24 UTC, riivx approved these changes
looks great, i approve

2024-02-08 14:25 UTC, danilwhale commented
![image](https://github.com/sunset-mod/Sunset/assets/61111955/b7a21a22-7656-4248-bb5c-3c12b4f8600a)

2024-02-08 19:51 UTC, mufaroxyz commented
LGTM

2024-02-09 09:32 UTC, Ushie requested changes

2024-02-09 09:32 UTC, Ushie commented on src/ui/settings/pages/General.tsx
> +    { discord: DISCORD_SERVER, github: GITHUB, whose: "Sunset" },
"whose" is a bad key name, use something more semantically correct

something like this:

```json
[
    "Sunset": {
        discord: DISCORD_SERVER,
        github: GITHUB
   },
    "Vendetta": {
        ....
   }
]
```

Or
```json
[
    {
        name: "Sunset",
        ...
    },
    {
        name: "Vendetta",
        ....
    }
]
```

Excuse the formatting, I'm on mobile atm

2024-02-09 09:33 UTC, Ushie requested changes
Improve the PR title to represent what it actually does

2024-02-09 10:38 UTC, riivx commented
LGTM

2024-02-09 10:39 UTC, Ushie requested changes

2024-02-09 10:39 UTC, Ushie commented on src/ui/settings/pages/General.tsx
> +                {links.map((link) => (
Why map? you could forEach

2024-02-09 10:45 UTC, danilwhale commented on src/ui/settings/pages/General.tsx
> +                {links.map((link) => (
isnt map easier?

2024-02-09 11:04 UTC, mufaroxyz commented on src/ui/settings/pages/General.tsx
> +                {links.map((link) => (
For more reference: map returns the iterated values while forEach does not return to the scope it is called in. Hence why it is required to use map in JSX

https://react.dev/learn/rendering-lists

2024-02-09 15:01 UTC, riivx commented on src/ui/settings/pages/General.tsx
> +                {links.map((link) => (
then i guess it's resolved

2024-02-09 16:26 UTC, mufaroxyz commented on src/ui/settings/pages/General.tsx
> +                {links.map((link) => (
> then i guess it's resolved

I think so. You can merge that I guess

2024-02-09 17:02 UTC, Ushie approved these changes

2024-02-09 17:02 UTC, Ushie commented
The PR should specify that this is about, settings page

2024-02-09 17:18 UTC, riivx commented
changed the title, thanks for PR!

2024-02-09 17:20 UTC, merged